PersonelMVCUI/Controllers/SecurityController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PersonelMVCUI.Controllers
{
    public class SecurityController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Kullanici kullanici)
        {
            var kullaniciInDb = db.Kullanici.FirstOrDefault(x=>x.Ad == kullanici.Ad && x.Sifre == kullanici.Sifre);
            if (kullaniciInDb != null)
            {
                FormsAuthentication.SetAuthCookie(kullaniciInDb.Ad, false);
                return RedirectToAction("Index","Departman");


            }
            else
            {
                ViewBag.Mesaj = "Kullanıcı adı veya şifre hatalı.";
                return View();
            }
            
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

PersonelMVCUI/Views/Security/Login.cshtml
@model PersonelMVCUI.Models.EntityFramework.Kullanici
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <h2>Lütfen giriş yapınız...</h2>
    @ViewBag.Mesaj
    <div class="container">
        @using (Html.BeginForm("Login", "Security", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Ad)
                @Html.TextBoxFor(m => m.Ad, new { @class = "form-control", placeholder = "Kullancı Adı" })
            </div>
            <div>
                @Html.LabelFor(m => m.Sifre)
                @Html.PasswordFor(m => m.Sifre, new { @class = "form-control", placeholder = "Parola" })
            </div>

            <button type="submit" class="btn btn-block btn-success">Giriş Yap</button>
        }


    </div>
</body>
</html>