PersonelMVCUI/Models/EntityFramework/Personel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Id { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<short> Maas { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}

PersonelMVCUI/Controllers/PersonelController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class PersonelController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();
        // GET: Personel
        public ActionResult Index()
        {
            var model = db.Personel.Include(x=>x.Departman).ToList(); // EAGER LOADING : Personel tablosu ile Departman tablosunu joinleyecek 
            return View(model);
        }
        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = new Personel()
            };
            return View("PersonelForm",model);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            
            if (!ModelState.IsValid) {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model);
            }
        


            if(personel.Id == 0)// Ekleme işlemi
               db.Personel.Add(personel);
            else // Güncelleme İşlemi
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm",model);

        }

        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            db.Personel.Remove(silinecekPersonel);
            if (silinecekPersonel == null)
                HttpNotFound();
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

PersonelMVCUI/Views/Personel/Index.cshtml
@model List<PersonelMVCUI.Models.EntityFramework.Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.ActionLink("Yeni Personel", "Yeni", null,new {@class="btn btn-success"})
<h2>Personel Listesi</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>>Departman</th>
            <th>Maaş</th>
            <th>Yaş</th>
            <th>Doğum Tarihi</th>
            <th>Cinsiyet</th>
            <th>Evlilik Durumu</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var personel in Model)
            {
                <tr>
                    <td>@personel.Ad</td>
                    <td>@personel.Soyad</td>
                    <td>@personel.Departman.Ad</td>
                    <td>@personel.Maas</td>
                    <td>@(DateTime.Now.Year - personel.DogumTarihi.Value.Year)</td>
                    <td>@personel.DogumTarihi.Value.ToString("dd-MM-yyyy")</td>
                    <td>@(personel.Cinsiyet == true ? "Erkek" : "Kadın")</td>
                    <td>@(personel.EvliMi == true ? "Evli" : "Bekar")</td>
                    <td>@Html.ActionLink("Güncelle","Guncelle",new {id = personel.Id}, new {@class="btn btn-success"})</td>
                    <td>@Html.ActionLink("Sil", "Sil", new { id = personel.Id }, new { @class = "btn btn-warning" })</td>
                </tr>
            }
    </tbody>
</table>

PersonelMVCUI/Views/Personel/PersonelForm.cshtml
@model PersonelMVCUI.ViewModels.PersonelFormViewModel
@{
    ViewBag.Title = "PersonelForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* Burada ViewModel kullanmamızın tek esprisi liste şeklinde departmanlarımızın lazım olmasıdır.  *@

<h2>PersonelForm</h2>

@using (Html.BeginForm("Kaydet", "Personel", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Ad)
        @Html.TextBoxFor(m => m.Personel.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Personel.Ad)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Soyad)
        @Html.TextBoxFor(m => m.Personel.Soyad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.DepartmanId)
        @Html.DropDownListFor(m => m.Personel.DepartmanId, new SelectList(Model.Departmanlar, "Id", "Ad"), "Departman Seçiniz", new
       { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Personel.Id)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Maas)
        @Html.TextBoxFor(m => m.Personel.Maas, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.DogumTarihi)
        @Html.TextBoxFor(m => m.Personel.DogumTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date",onchange="CheckDateTypeIsValid(this)" })
    </div>
    <div class="radio">
        <label>
            @Html.RadioButtonFor(m => m.Personel.Cinsiyet, true) Erkek
        </label>
        <label>
            @Html.RadioButtonFor(m => m.Personel.Cinsiyet, false) Kadın
        </label>
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.Personel.EvliMi) Evliyseniz seçiniz
        </label>
    </div>
    @Html.HiddenFor(m => m.Personel.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>
}


@section scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}